builders:
  # name of the builder
  odooProviderModelBuilder:
    # library URI containing the builder
    import: "package:odoo_provider_builder/odoo_provider_builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ['odooProviderModelBuilder']
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart":["provider.g.part"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: cache
    # combine the parts from each builder into one part file
    applies_builders: ["source_gen|combining_builder"]